### ISSUE TITLE
Items needed for launch

### ISSUE THREAD

**Issue by longmeaghan** [longmeaghan/ml_portfolio#28]
Launch should be on Tuesday August 7th (two days before I leave for Siggraph). Items that will needed are the following.

**Wellington**
- [x] Fixed left + header column #10 
- [x] Removing .php on website #6
- [x] Light gallery #29  
- [x] Upload website to server #27 

**Meaghan**
- [x] Add favicon #30 
- [x] Add footer #31 
- [x] Add images + copy #14 
- [x] Fix header margins + logo (after #10 is complete)
- [x] Add all .php case studies (after #10 is complete)
